{
 "title": "demo variables",
 "time": { "from": "2023-08-11T18:59:58.692Z", "to": "2023-08-11T19:01:31.594Z" },
 "templating": {
  "list": [
   { "name": "collector", "query": { "query": "label_values(job) " } },
   {
    "name": "github_org",
    "query": {
     "query": "label_values({job=~\"$collector\"}, github_org) "
    }
   },
   {
    "name": "repo",
    "query": {
     "query": "label_values({github_org=~\"$github_org\",job=~\"$collector\"}, repository_name) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Repo Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "git_repository_count{github_org=~\"$github_org\", service_name=~\"$collector\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Branch Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "git_repository_branch_count{github_org=~\"$github_org\", service_name=~\"$collector\", repository_name=~\"$repo\"}",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Age",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "git_repository_branch_time{github_org=~\"$github_org\", service_name=~\"$collector\", repository_name=~\"$repo\"}",
     "legendFormat": "{{repository_name}}/{{branch_name}}"
    }
   ]
  }
 ]
}