{
 "title": "demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Repo Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "git_repository_count", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Branch Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "git_repository_branch_count", "legendFormat": "{{repository_name}}" }
   ]
  },
  {
   "title": "Branch Age",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "git_repository_branch_time",
     "legendFormat": "{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Age Per Repo In Days",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(repository_name) (git_repository_branch_time > 0) / 24",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Count",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(organization_name) (git_repository_branch_count)",
     "legendFormat": "{{repository_name}}"
    }
   ]
  }
 ]
}