{
 "title": "DORA stuff",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "organization",
    "query": {
     "query": "label_values(organization_name)"
    }
   },
   {
    "name": "repo",
    "query": {
     "query": "label_values({organization_name=\"$organization\"},repository_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Change Failure Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A)*100", "type": "math" }
   ]
  },
  { "title": "Lead Time For Changes In Hours", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Lead Time to Changes Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{sha!=\"\", repository_owner=\"$organization\", repository_name=\"$repo\", action=\"closed\"}"
    },
    {
     "expr": "{created_at!=\"\",action=\"\",repository_name=\"$repo\", repository_owner=\"$organization\"} |= ``"
    }
   ]
  },
  {
   "title": "Average Lead Time To Changes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{sha!=\"\", repository_owner=\"$organization\", repository_name=\"$repo\", action=\"closed\"}"
    },
    {
     "expr": "{created_at!=\"\",action=\"\",repository_name=\"$repo\", repository_owner=\"$organization\"} |= ``"
    }
   ]
  },
  { "title": "Time to Restore Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{repository_name=~\"$repo\",repository_owner=~\"$organization\"}"
    }
   ]
  },
  {
   "title": "Time To Restore Service Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "{repository_name=~\"$repo\",repository_owner=~\"$organization\"}"
    }
   ]
  },
  {
   "title": "Average Time to Restore Service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "{repository_name=~\"$repo\",repository_owner=~\"$organization\"}"
    }
   ]
  },
  { "title": "Deployment Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{status=\"success\",repository_name=~\"$repo\",repository_owner=~\"$organization\"}"
    }
   ]
  },
  {
   "title": "Deployments Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "{status=\"success\", repository_name=~\"$repo\", repository_owner=~\"$organization\"}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{status=\"success\", repository_name=~\"$repo\", repository_owner=~\"$organization\"}"
    }
   ]
  }
 ]
}